### ISSUE TITLE
Console.log published?

### ISSUE THREAD

**Issue by JonasJonny** [exponent/exponent#64]
Is console.log removed from source code when app is published to exp.host?

**Comment by JonasJonny** [comment]
&minify=true
I guess so ;).

**Comment by jesseruder** [comment]
No it's not, why would it be?

**Comment by JonasJonny** [comment]
@jesseruder No I am confused. I think if we publish request:/main.bundle?dev=false&minify=true with &minify=true, then console logs are removed. I hope they are.

**Comment by ide** [comment]
Removing console.log statements blindly is dangerous unless you can prove that each expression passed to the console.log call has no side-effects and can't throw and exception. Code paths that differ between development and production commonly introduce bugs and are extra hard to debug because they don't show up during development.

You should replace console.log with a no-op function but still keep all of the calls in your production app.

**Comment by JonasJonny** [comment]
Aaah, good to know. 
The console.logs which I don't want to in production should be removed/commented out "manually".
Thanks.
