### ISSUE TITLE
How are env variables (secrets) used?

### ISSUE THREAD

**Issue by redgenie** [exponent/exponent#83]
In react-native, you could use `react-native-config`. But since it requires touching iOS and Android files, it won't be possible to use it with Expo. How are you supposed to feed different env variables, especially those that hold api keys?

**Comment by terribleben** [comment]
Hi, it looks like `react-native-config` reads the local `.env` file and then, at build time, writes a `#define` (or android equivalent) in your native code, which is then exported to JS.

I want to clarify that this tool *does not make your secrets safe*. It just puts them in your native binary every time you build.

That being said: At the moment we don't offer anything exactly like that for Expo, but nothing's stopping you from writing similar automation for exposing `.env` constants to JS, by just generating a JS object and skipping the native layer. This wouldn't be any more or less secure. But I don't know of an existing tool which does exactly that.

If your main goal is to avoid committing secrets to source control, you're best off just exposing them directly to JS from some particular file, then gitignoring that file. This behavior isn't unique to `.env`.

**Comment by offerijns** [comment]
@redgenie I happened to come across this issue, looking for the same solution. However, I found this alternative: https://github.com/zetachang/react-native-dotenv. This tool doesn't use native code, since it is simply implemented as a Babel plugin. So you can use it with Expo!

**Comment by PaddyLock** [comment]
@redgenie I have installed react-native-dotenv with my React Native Expo app. I have created a .env and .env.production. This works fine for previewing in simulator on my local machine, but when I share via expo it uses the same .env rather than .env.production. How do I get it to use the correct file?

**Comment by lukewendling** [comment]
@PaddyLock I have the same question today. Looking at source of react-native-dotenv, it relies on the env var BABEL_ENV. From https://babeljs.io/docs/usage/babelrc/ - babels uses BABEL_ENV and falls back to NODE_ENV... so I'm currently including .env.production by running `BABEL_ENV=production yarn run exp start`

**Comment by btroia** [comment]
@PaddyLock how have you configured your `package.json` to get this to work? I added `exp` to my `devDependencies`:

```
"devDependencies": {
    ...
    "exp": "^52.0.3",
    ...
  },
  "scripts": {
    "exp": "exp"
  },
```

and have a separate `.env.production` config but when I try running `BABEL_ENV=production yarn run exp start` , it still loads `.env` instead of `.env.production`. Any idea what I might be missing? Thx.

**Comment by btroia** [comment]
@lukewendling Thanks. Looks like my issue was trying to use `BABEL_ENV=production yarn run exp start` - the production flag can only recognized when building the binary (`BABEL_ENV=production yarn run exp build:ios`)
